<!-- SALE PAGE UPDATES - HAWK BANNER !-->
<!-- desktop hawk second top banner [08WKS1-3Y17]!-->
<div style="position:relative;max-width:100%;padding:0 0 15px 0;margin:0;">
	<div id="asi-sale-hero">
		<img alt="10% off made to mix furniture. prices reflect discount." class="img-responsive" src="https://asf.scene7.com/is/image/ASF/Hawk_08WK1Y17_GoingOnNow?qlt=84,1&amp;op_sharpen=1" style="padding-bottom:0px;width:100% !important;max-width:100% !important;">
	</div>
	<div class="asi-section-content text-center" style="position:relative;padding-top:10px;">
		<div class="col-md-12 col-sm-12 col-xs-12"><div class="asi-section-content-wrapper" style="padding:10px 0px;">
			<h3 class="asi-section-title asi-display-3 text-center text-uppercase" style="color:#121212;padding-bottom:6px;font-size:44px !important;color:#121212;word-wrap:break-word;margin:0px auto;font-family:'Knockout-HTF29-JuniorLiteweight','ProximaNova-Semibold', 'ProximaNova-Semibold', sans-serif;letter-spacing:1px;line-height:1;">CUSTOMIZE YOUR DESIGN</h3>
				<span class="asi-section-subtitle" style="display:block;position:relative;">
					<div class="asi-heading-rule" style="letter-spacing:1px;text-align:center;color:#3a3a3b;text-transform:uppercase;font-size:18px !important;font-family:'Proxima Nova Bold','ProximaNova-Bold','Proxima-Nova-Bold',sans-serif !important;background-color:#ffffff;"><span class="asi-heading-rule-text" style="padding:0 15px;color:#3a3a3b;background:#ffffff !important;position:relative;z-index:2;">MIX &amp; MAKE IT YOU</span>
					</div>
				</span>
			</div>
		</div>
	</div>
	<div id="asi-sale-feature-1">
		<div class="col-md-4 col-sm-4 col-xs-12">
			<a href="/make-it-you/custom-living-room-furniture" title="10% custom living rooms"><img alt="10% off mix custom living rooms" class="img-responsive" src="https://asf.scene7.com/is/image/ASF/sale-page-getaway-lr.jpg"></a>
		</div>
		<div class="col-md-4 col-sm-4 col-xs-12">
			<a href="/make-it-you/custom-bedroom-furniture" title="10% custom bedrooms"><img alt="10% off mix custom bedrooms" class="img-responsive" src="https://asf.scene7.com/is/image/ASF/sale-page-getaway-br.jpg"></a>
		</div>
		<div class="col-md-4 col-sm-4 col-xs-12">
			<a href="/make-it-you/custom-dining-room-furniture" title="10% custom dining rooms"><img alt="10% off mix custom dining rooms" class="img-responsive" src="https://asf.scene7.com/is/image/ASF/sale-page-getaway-dr.jpg"></a>
		</div>
	</div>
	<div class="clear clearfix"></div>
<div id="asi-sale-feature-2">
<div class="asi-section-content text-center" style="position:relative;padding-top:15px;"><div class="asi-section-content-wrapper" style="padding:0;"><h3 class="asi-section-title asi-display-3 text-center text-uppercase" style="color:#121212;padding-bottom:0px;font-size:44px !important;color:#121212;word-wrap:break-word;margin:0px auto;font-family:'Knockout-HTF29-JuniorLiteweight','ProximaNova-Semibold', 'ProximaNova-Semibold', sans-serif;letter-spacing:1px;line-height:1;">OUR BEST SELLERS JUST GOT BETTER</h3><span class="asi-section-subtitle" style="display:block;position:relative;"><div class="asi-heading-rule" style="letter-spacing:1px;text-align:center;color:#3a3a3b;text-transform:uppercase;font-size:18px !important;font-family:'Proxima Nova Bold','ProximaNova-Bold','Proxima-Nova-Bold',sans-serif !important;background-color:#ffffff;"><span class="asi-heading-rule-text" style="padding:0 15px;color:#3a3a3b;background:#ffffff !important;position:relative;z-index:2;">SAVE ON YOUR FAVES</span></div></span></div></div><div class="clear clearfix"></div><div class="col-md-3 col-sm-3 col-xs-6" style="padding-top:10px;"><a href="on-sale?searchWithin=gabe" title="10% best sellers - the gabe collection"><img alt="10% the gabe collection" class="img-responsive" src="https://asf.scene7.com/is/image/ASF/sale-page-bestseller-1.jpg"></a></div><div class="col-md-3 col-sm-3 col-xs-6" style="padding-top:10px;"><a href="on-sale?searchWithin=brittney" title="10% best sellers - the brittney collection"><img alt="10% the brittney collection" class="img-responsive" src="https://asf.scene7.com/is/image/ASF/sale-page-bestseller-2.jpg"></a></div><div class="col-md-3 col-sm-3 col-xs-6" style="padding-top:10px;"><a href="on-sale?searchWithin=angelina" title="10% best sellers - the angelina collection"><img alt="10% the angelina collection" class="img-responsive" src="https://asf.scene7.com/is/image/ASF/sale-page-bestseller-4.jpg"></a></div><div class="col-md-3 col-sm-3 col-xs-6" style="padding-top:10px;"><a href="on-sale?searchWithin=malibu" title="10% best sellers - the malibu collection"><img alt="10% the malibu collection" class="img-responsive" src="https://asf.scene7.com/is/image/ASF/sale-page-bestseller-3.jpg"></a></div></div><div class="clear clearfix"></div></div>
<style>.asi-heading-rule:before,.asi-heading-rule::before{position:absolute;content:'';left:0;right:0;top:50%;border-bottom:1px solid #3a3a3b;height:1px;-webkit-transform:translateY(-50%);-ms-transform:translateY(-50%);transform: translateY(-50%);}</style>

<!-- mobile hawk second top banner [08WKS1-3Y17]!-->
<div style="position:relative;max-width:100%;padding:0 0 15px 0;margin:0;"><div id="asi-sale-hero"><img alt="10% off made to mix furniture. prices reflect discount." class="img-responsive" src="https://asf.scene7.com/is/image/ASF/M_Hawk_08WK1Y17_GoingOnNow?qlt=84,1&amp;op_sharpen=1" style="padding-bottom:0px;width:100% !important;max-width:100% !important;"></div><div class="asi-section-content text-center" style="position:relative;padding-top:10px;"><div class="col-md-12 col-sm-12 col-xs-12"><div class="asi-section-content-wrapper" style="padding:10px 0px;"><h3 class="asi-section-title asi-display-3 text-center text-uppercase" style="color:#121212;padding-bottom:6px;font-size:24px !important;color:#121212;word-wrap:break-word;margin:0px auto;font-family:'Knockout-HTF29-JuniorLiteweight','ProximaNova-Semibold','ProximaNova-Semibold',sans-serif;letter-spacing:1px;line-height:1;">CUSTOMIZE YOUR DESIGN</h3><span class="asi-section-subtitle" style="display:block;position:relative;"><div class="asi-heading-rule" style="letter-spacing:1px;text-align:center;color:#3a3a3b;text-transform:uppercase;font-size:12px !important;font-family:'Proxima Nova Bold','ProximaNova-Bold','Proxima-Nova-Bold',sans-serif !important;background-color:#ffffff;"><span class="asi-heading-rule-text" style="padding:0 15px;color:#3a3a3b;background:#ffffff !important;position:relative;z-index:2;">MIX &amp; MAKE IT YOU</span></div></span></div></div></div><div id="asi-sale-feature-1"><div class="col-md-4 col-sm-4 col-xs-12" style="padding-top:10px;"><a href="/make-it-you/custom-living-room-furniture" title="10% custom living rooms"><img alt="10% off mix custom living rooms" class="img-responsive" src="https://asf.scene7.com/is/image/ASF/sale-page-getaway-lr-m.jpg"></a></div><div class="col-md-4 col-sm-4 col-xs-12" style="padding-top:10px;"><a href="/make-it-you/custom-bedroom-furniture" title="10% custom bedrooms"><img alt="10% off mix custom bedrooms" class="img-responsive" src="https://asf.scene7.com/is/image/ASF/sale-page-getaway-br-m.jpg"></a></div><div class="col-md-4 col-sm-4 col-xs-12" style="padding-top:10px;"><a href="/make-it-you/custom-dining-room-furniture" title="10% custom dining rooms"><img alt="10% off mix custom dining rooms" class="img-responsive" src="https://asf.scene7.com/is/image/ASF/sale-page-getaway-dr-m.jpg"></a></div></div><div class="clear clearfix"></div>
<div id="asi-sale-feature-2"><div class="asi-section-content text-center" style="position:relative;padding-top:15px;"><div class="asi-section-content-wrapper" style="padding:0;"><h3 class="asi-section-title asi-display-3 text-center text-uppercase" style="color:#121212;padding-bottom:0px;font-size:22px !important;color:#121212;word-wrap:break-word;margin:0px auto;font-family:'Knockout-HTF29-JuniorLiteweight','ProximaNova-Semibold', 'ProximaNova-Semibold', sans-serif;letter-spacing:1px;line-height:1;">OUR BEST SELLERS JUST GOT BETTER</h3><span class="asi-section-subtitle" style="display:block;position:relative;"><div class="asi-heading-rule" style="letter-spacing:1px;text-align:center;color:#3a3a3b;text-transform:uppercase;font-size:12px !important;font-family:'Proxima Nova Bold','ProximaNova-Bold','Proxima-Nova-Bold',sans-serif !important;background-color:#ffffff;"><span class="asi-heading-rule-text" style="padding:0 15px;color:#3a3a3b;background:#ffffff !important;position:relative;z-index:2;">SAVE ON YOUR FAVES</span></div></span></div></div><div class="clear clearfix"></div><div class="col-md-3 col-sm-3 col-xs-6" style="padding-top:10px;"><a href="on-sale?searchWithin=gabe" title="10% best sellers - the gabe collection"><img alt="10% the gabe collection" class="img-responsive" src="https://asf.scene7.com/is/image/ASF/sale-page-bestseller-1-m.jpg"></a></div><div class="col-md-3 col-sm-3 col-xs-6" style="padding-top:10px;"><a href="on-sale?searchWithin=brittney" title="10% best sellers - the brittney collection"><img alt="10% the brittney collection" class="img-responsive" src="https://asf.scene7.com/is/image/ASF/sale-page-bestseller-2-m.jpg"></a></div><div class="col-md-3 col-sm-3 col-xs-6" style="padding-top:10px;"><a href="on-sale?searchWithin=angelina" title="10% best sellers - the angelina collection"><img alt="10% the angelina collection" class="img-responsive" src="https://asf.scene7.com/is/image/ASF/sale-page-bestseller-4-m.jpg"></a></div><div class="col-md-3 col-sm-3 col-xs-6" style="padding-top:10px;"><a href="on-sale?searchWithin=malibu" title="10% best sellers - the malibu collection"><img alt="10% the malibu collection" class="img-responsive" src="https://asf.scene7.com/is/image/ASF/sale-page-bestseller-3-m.jpg"></a></div></div></div><div class="clear clearfix"></div>
<style>.asi-heading-rule:before,.asi-heading-rule::before{position:absolute;content:'';left:0;right:0;top:50%;border-bottom:1px solid #3a3a3b;height:1px;-webkit-transform:translateY(-50%);-ms-transform:translateY(-50%);transform: translateY(-50%);}</style>